version: "3"
services:
    legion-ms-auth:
        container_name: legion-ms-auth
        extra_hosts:
            - host.docker.internal:host-gateway
        user: 1000:1000
        build:
            context: ../../../.
            dockerfile: config/_inf/dev-user-verify/Dockerfile
        networks:
            - legion-network
        volumes:
            - 'user-verify-docker-sync:/var/www/html'
networks:
    legion-network:
        external: true

volumes:
    user-verify-docker-sync:
        external: true