nelmio_api_doc:
    documentation:
        info:
            title: Order MS
            description: MS for orders
            version: 1.0.0
    areas:
        path_patterns:
            - ^/back-api/order(?!/doc.json$)
