#security:
#    providers:
#        users_in_memory: { memory: null }
#    firewalls:
#        main:
#            pattern: ^/
#            anonymous: lazy
#            stateless: true
#            guard:
#                authenticators:
#                    - Legion\LegionBundle\Service\TokenAuthenticator
#    access_control:
#        - { path: ^/back-api/order/doc.json, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
##        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }