# The ConfigMap MUST be created first for the ingress controller to be able to
# find it when the Ingress object is created.

apiVersion: v1
kind: ConfigMap
metadata:
    name: legion-ms-auth-ingress-cm
data:
    SCRIPT_FILENAME: "/var/www/html/public/index.php"

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
        nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
        nginx.ingress.kubernetes.io/fastcgi-params-configmap: "legion-ms-auth-ingress-cm"
    name: legion-ms-auth-ingress
spec:
    rules:
        -   host: lfc-stg.wow-carry.com
            http:
                paths:
                    -   path: /back-api/auth
                        backend:
                            serviceName: legion-ms-auth-service
                            servicePort: 9000