apiVersion: v1
kind: Service
metadata:
    name: legion-ms-user-service
spec:
    type: ClusterIP
    ports:
        -   port: 9000
            protocol: TCP
            targetPort: 9000
    selector:
        app: legion-ms-user