version: "3"
services:
    legion-ms-user:
        container_name: legion-ms-user
        extra_hosts:
            - host.docker.internal-user:host-gateway
        user: 1000:1000
        build:
            context: ../../../.
            dockerfile:  config/_inf/dev-user/Dockerfile
        networks:
            - legion-network
        volumes:
            - 'user-docker-sync:/var/www/html'
networks:
    legion-network:
        external: true


volumes:
    user-docker-sync:
        external: true